### ISSUE TITLE
Deprecated: cabal-dev & add-source

### ISSUE THREAD

**Issue by duplex143** [keera-studios/gtk-helpers#2]
```
$ cabal-dev install gtk-helpers
```
It seems that cabal-dev is now deprecated.
I've  installed gtk-helpers with
` $ cabal install gtk-helpers`
But when I'm running the final command, I'm getting the error 
ghc: can't find a package database at some location.

**Comment by ivanperez-keera** [comment]
Thanks a lot for pointing this out. The article needs to be updated.

If you have installed outside a sandbox, then you should be able to just run:
```
ghc --make BoardMain.hs
```
However, I would personally recommend that you use sandboxes to keep your system clean. An example of how to do this with the new cabal sandboxes follows (I'm using gtk2 but that doesn't matter much):
```
git clone https://github.com/keera-studios/gtk-helpers.git
cd gtk-helpers/gtk2
cabal sandbox init
cabal install
cd examples/lights-off/
cabal sandbox --sandbox=../../.cabal-sandbox/ init
cabal install IfElse
cabal exec -- ghc --make BoardMain.hs
```

The idea behind this is that we are:
* Creating a sandbox (or contained environment for haskell stuff) inside the directory gtk-helpers/gtk2.
* Then we are installing the package gtk-helpers in that directory (cabal install finds the only .cabal file in that dir).
* We move into examples/lights-off, and tell cabal to use the sandbox in gtk-helpers/gtk2 for anything we run in this directory.
* Finally, we compile BoardMain.hs. We are missing a package, so we install that first. Then we use `cabal exec` to help GHC find the sandbox where all the packages have been installed.

I think this package would benefit from including the examples as part of the cabal file, so that people can just do `cabal install gtk-helpers -fexamples`. If you feel like contributing that, I'd be very happy to help you put it together so that you can submit a pull request :)

**Comment by csumanth98** [comment]
When I'm following the similar instructions for peg-solitaire, I'm getting the following errors
```
BoardMain.hs:39:21: error:
    Not in scope: type constructor or class ‘Board’

BoardMain.hs:39:31: error:
    Not in scope: type constructor or class ‘Tile’

BoardMain.hs:39:36: error:
    Not in scope: type constructor or class ‘Peg’

BoardMain.hs:43:20: error:
    Not in scope: type constructor or class ‘Board’

BoardMain.hs:43:30: error:
    Not in scope: type constructor or class ‘Tile’

BoardMain.hs:43:35: error:
    Not in scope: type constructor or class ‘Peg’

BoardMain.hs:46:16: error:
    Not in scope: type constructor or class ‘Board’

BoardMain.hs:46:26: error:
    Not in scope: type constructor or class ‘Tile’

BoardMain.hs:46:31: error:
    Not in scope: type constructor or class ‘Peg’
```
By the way, what's
`cabal install IfElse`
Do I need to install anything for peg-solitaire?

**Comment by csumanth98** [comment]
When I'm following the similar instructions for peg-solitaire, I'm getting the following errors

BoardMain.hs:39:21: error:
    Not in scope: type constructor or class ‘Board’

BoardMain.hs:39:31: error:
    Not in scope: type constructor or class ‘Tile’

BoardMain.hs:39:36: error:
    Not in scope: type constructor or class ‘Peg’

BoardMain.hs:43:20: error:
    Not in scope: type constructor or class ‘Board’

BoardMain.hs:43:30: error:
    Not in scope: type constructor or class ‘Tile’

BoardMain.hs:43:35: error:
    Not in scope: type constructor or class ‘Peg’

BoardMain.hs:46:16: error:
    Not in scope: type constructor or class ‘Board’

BoardMain.hs:46:26: error:
    Not in scope: type constructor or class ‘Tile’

BoardMain.hs:46:31: error:
    Not in scope: type constructor or class ‘Peg’
By the way, what's
cabal install IfElse
Do I need to install anything for peg-solitaire?

**Comment by csumanth98** [comment]
lights-off and tic-tac-toe are working fine though.
There seems to be an issue with peg-solitaire and peg-solitaire-english.
@ivanperez-keera

**Comment by sadhubalaamarnath** [comment]
@ivanperez-keera 
Even I am facing the same issue. Thanks, @csumanth98  for pointing out.

**Comment by ivanperez-keera** [comment]
I don't understand what just happened. Where are the comments from Sumanth Culli and Sadhu Amarnath? Did you both get peg-solitaire and peg-solitaire-english to compile?

**Comment by duplex143** [comment]
@ivanperez-keera 
Our code is working perfectly fine except for small issues. 
1)We haven't imported `PegSolitaire` to `BoardMain.hs`
2)Since `Board` isn't defined, we also need to import the module `Graphics.UI.Gtk.Board.TiledBoard` 
3)We also need to import the modules `Data.Maybe` and `Control.Monad` for the functions `when`, `isJust` and `isNothing` to be in scope.
We've also observed that creating sandbox is _essential_ and installing `gtk-helpers` inside the sandbox isn't needed (We're not sure about creating sandbox, btw we've installed gtk-helpers globally using `cabal install gtk-helpers`)

So, we've added 
`import PegSolitaire
import Graphics.UI.Gtk.Board.TiledBoard
import Data.Maybe
import Control.Monad` to BoardMain.hs and it worked like a charm.

**Comment by ivanperez-keera** [comment]
Good. Glad to hear you got it working. I'll update the article.

Would you like to submit a pull request so that this gets fixed permanently, and maybe we can also add the examples to the cabal file and I can configure travis to check this during testing?

**Comment by duplex143** [comment]
@ivanperez-keera 
As for submitting pull requests, we're still newbies to Haskell programming and might not be of much help to you. 
We're also very grateful for your contribution to Haskell packages, especially to `gtk-helpers`, `qt` and `yampa`.

**Comment by ivanperez-keera** [comment]
I'm very happy to see that it's useful.

It's no problem that you are newbies. I can modify your contributions before merging them. It's one more way to start, but it is totally your choice. If you want to give it a try:
* Fork this project to your user.
* git clone your fork of gtk-helpers.
* Modify the files with the changes you've mentioned to make peg-solitaire and peg-solitaire-english compile.
* git add the files you've modified.
* git commit. Write a meaningful message. Refer to this issue in the commit message (by URL, I guess).
* git push
* Go to github on your browser and send a pull request.

**Comment by duplex143** [comment]
@ivanperez-keera 
Have I done the procedure correctly?
I can't figure out the mistake in `peg-solitaire-english`.
It's giving the following error.

```
    • Expecting one fewer argument to ‘Board Int Player tile’
       Expected kind ‘* -> *’, but ‘Board Int Player tile’ has kind ‘*’
    • In the type signature:
        attemptMove :: Board Int Player tile Piece
                       -> (Int, Int) -> (Int, Int) -> IO ()
```

**Comment by duplex143** [comment]
@ivanperez-keera 
I request you to update the instructions in `http://keera.co.uk/blog/2013/03/19/creating-board-games-in-haskell/#result`
